base_model:
  N_ESTIMATORS: 100
  MAX_DEPTH: 3
  LEARNING_RATE: 0.1

training:
  N_ESTIMATORS: [100, 200]
  MAX_DEPTH: [3, 5]
  LEARNING_RATE: [0.01, 0.1]
  SCORING: "r2"
  N_JOBS: -1
  CV: 3
  VERBOSE: 2